ip1=eval(input('Enter something : '))
print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
# ip1=eval(input('Enter something : '))
# print('type is: ',type(ip1))
ip2=eval('10+90*2')
print('value  is: ',ip2)
print('type  is: ',type(ip2))
